### ISSUE TITLE
[Suggestion] Add support for secondary context Twitter account

### ISSUE THREAD

**Issue by ThePoptartCrpr** [corbindavenport/tootbot#81]
Having the option to have a second context account in the old memebot was incredibly useful. Could be a good long-term goal

**Comment by corbindavenport** [comment]
Support for context accounts was dropped in Tootbot 1.0 for two main reasons:

- Managing two different Twitter API sessions (one for main + one for context) made the codebase somewhat complicated, and it would only be worse now that Mastodon posting is also supported.
- Twitter now sorts replies algorithmically instead of chronologically, so the context reply was often hidden below dozens of other tweets. This obscured the source material and frequently lead to people thinking the bot accounts weren't crediting content.

Linking the Reddit post directly in the original tweet fixes both problems, and the shortlink hardly takes up any space, so I don't see a reason to bring back context accounts.
